gateway:
  ip: 18.189.150.177

myEureka:
  password: test

ribbon:
  ReadTimeout: 120000

zuul:
  host:
    socket-timeout-millis: 90000
    
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 242000

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.31.22.137:8010/eureka
  instance:
    preferIpAddress: true

token:
  expiration_time: 86400000 # 1 days
  secret: otpekfkelemdmsmdmem8584k4834odABC
  
login:
  url:
    path: /users/login

albums:
  url: http://ALBUMS-WS/users/%s/albums
  exceptions:
    albums-not-found: User albums not found!!!

spring:
  cloud:
    inetutils:
      ignored-interfaces:
        - eth0
        - eth1
        - eth2
        - eth3
        - lo